#!/usr/bin/env bash
#
# pnpm processes:triage [--dry-run]
#
# Runs the processes-triage skill end-to-end:
#   1. Ensures clean working tree on main, pulls latest
#   2. Creates a branch
#   3. Launches Claude Code interactively with the triage prompt — you see it
#      work and can redirect mid-session. Exit with /exit or Ctrl-D when done.
#   4. If anything in data/ changed → commits, pushes, opens PR
#   5. If nothing changed → deletes the branch and returns to main
#
# --dry-run:
#   Skips the main sync, branch creation, commit, push, and PR steps.
#   Runs the skill in place on the current branch and shows the diff. Useful
#   for iterating on the skill prompt or testing locally.
#
# Requires `claude` and `gh` on PATH (gh only when not --dry-run).

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    *) echo "Unknown arg: $arg"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

command -v claude >/dev/null || { echo "Error: 'claude' CLI not on PATH"; exit 1; }

if [ "$DRY_RUN" -eq 0 ]; then
  command -v gh >/dev/null || { echo "Error: 'gh' CLI not on PATH"; exit 1; }

  if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "Error: working tree not clean. Commit or stash first."
    git status --short
    exit 1
  fi
fi

DATE=$(date -u +%Y-%m-%d)

# ---------------------------------------------------------------------------
# Sync main + new branch (skipped in --dry-run)
# ---------------------------------------------------------------------------

if [ "$DRY_RUN" -eq 0 ]; then
  echo "→ Syncing main…"
  git fetch origin main --quiet
  git checkout main --quiet
  git pull --ff-only origin main --quiet

  BRANCH="processes-triage/${DATE}"
  # If branch already exists (re-running same day), append a suffix.
  if git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
    BRANCH="${BRANCH}-$(date -u +%H%M)"
  fi

  echo "→ Creating branch ${BRANCH}"
  git checkout -b "${BRANCH}" --quiet
else
  echo "→ Dry run on $(git rev-parse --abbrev-ref HEAD) — skipping main sync and branch creation."
fi

# ---------------------------------------------------------------------------
# Run the skill via headless Claude
# ---------------------------------------------------------------------------

PROMPT="Run the processes-triage skill. Read .cache/processes-audit.md (regenerate it first with pnpm processes:check). For each candidate, use atlas MCP tools to apply the research-doc methodology. Edit data/processes.json and data/processes-ignored.json directly. Do not commit or push — the wrapper script handles git. When the triage is complete, summarize what changed and stop."

echo "→ Launching Claude Code (interactive)…"
echo "  Exit with /exit or Ctrl-D when triage is complete."
echo ""
# Belt-and-suspenders: even though the prompt says "don't commit", block the
# git/gh write commands at the tool layer so the wrapper retains exclusive
# control over branch / commit / push / PR.
claude "${PROMPT}" \
  --disallowed-tools "Bash(git commit *)" "Bash(git push *)" "Bash(gh pr create *)" "Bash(gh issue close *)"

# ---------------------------------------------------------------------------
# Commit, push, PR
# ---------------------------------------------------------------------------

if git diff --quiet -- data/; then
  echo ""
  echo "→ No changes in data/ — nothing to triage."
  if [ "$DRY_RUN" -eq 0 ]; then
    git checkout main --quiet
    git branch -D "${BRANCH}" --quiet
  fi
  exit 0
fi

echo ""
echo "→ Changes in data/:"
git diff --stat -- data/

if [ "$DRY_RUN" -eq 1 ]; then
  echo ""
  echo "→ Dry run — leaving changes uncommitted. Inspect with: git diff -- data/"
  exit 0
fi

git add data/processes.json data/processes-ignored.json
git commit -m "chore: triage process inventory (${DATE})" --quiet

echo "→ Pushing ${BRANCH}…"
git push -u origin "${BRANCH}" --quiet

BODY=$(cat <<'EOF'
Automated triage of the curated process inventory (`data/processes.json`).

Generated by `pnpm processes:triage` — Claude ran the `processes-triage` skill against the current atlas state.

**Review:**
- `data/processes.json` — added entries / category / shape / status
- `data/processes-ignored.json` — entries the classifier surfaced but are not real processes

Merging this PR triggers `processes-autoclose.yml` which closes the open `processes-review` issue.
EOF
)

gh pr create \
  --title "Triage process inventory (${DATE})" \
  --body "${BODY}" \
  --base main \
  --head "${BRANCH}"

echo ""
echo "Done."
