#!/usr/bin/env bash
#
# pnpm processes:triage
#
# Runs the processes-triage skill end-to-end:
#   1. Ensures clean working tree on main, pulls latest
#   2. Creates a branch
#   3. Invokes Claude Code headlessly to run the skill
#   4. If anything in data/ changed → commits, pushes, opens PR
#   5. If nothing changed → deletes the branch and returns to main
#
# Requires `claude` and `gh` on PATH.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

command -v claude >/dev/null || { echo "Error: 'claude' CLI not on PATH"; exit 1; }
command -v gh >/dev/null     || { echo "Error: 'gh' CLI not on PATH"; exit 1; }

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: working tree not clean. Commit or stash first."
  git status --short
  exit 1
fi

# ---------------------------------------------------------------------------
# Sync main + new branch
# ---------------------------------------------------------------------------

echo "→ Syncing main…"
git fetch origin main --quiet
git checkout main --quiet
git pull --ff-only origin main --quiet

DATE=$(date -u +%Y-%m-%d)
BRANCH="processes-triage/${DATE}"
# If branch already exists (re-running same day), append a suffix.
if git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  BRANCH="${BRANCH}-$(date -u +%H%M)"
fi

echo "→ Creating branch ${BRANCH}"
git checkout -b "${BRANCH}" --quiet

# ---------------------------------------------------------------------------
# Run the skill via headless Claude
# ---------------------------------------------------------------------------

PROMPT="Run the processes-triage skill. Read .cache/processes-audit.md (regenerate it first with pnpm processes:check). For each candidate, use atlas MCP tools to apply the research-doc methodology. Edit data/processes.json and data/processes-ignored.json directly. Do not commit or push — the wrapper script handles git."

echo "→ Invoking Claude Code…"
echo "  Prompt: ${PROMPT}"
echo ""
claude -p "${PROMPT}"

# ---------------------------------------------------------------------------
# Commit, push, PR
# ---------------------------------------------------------------------------

if git diff --quiet -- data/; then
  echo ""
  echo "→ No changes in data/ — nothing to triage."
  git checkout main --quiet
  git branch -D "${BRANCH}" --quiet
  exit 0
fi

echo ""
echo "→ Changes in data/:"
git diff --stat -- data/

git add data/processes.json data/processes-ignored.json
git commit -m "chore: triage process inventory (${DATE})" --quiet

echo "→ Pushing ${BRANCH}…"
git push -u origin "${BRANCH}" --quiet

BODY=$(cat <<'EOF'
Automated triage of the curated process inventory (`data/processes.json`).

Generated by `pnpm processes:triage` — Claude ran the `processes-triage` skill against the current atlas state.

**Review:**
- `data/processes.json` — added entries / category / shape / status
- `data/processes-ignored.json` — entries the classifier surfaced but are not real processes

Merging this PR triggers `processes-autoclose.yml` which closes the open `processes-review` issue.
EOF
)

gh pr create \
  --title "Triage process inventory (${DATE})" \
  --body "${BODY}" \
  --base main \
  --head "${BRANCH}"

echo ""
echo "Done."
